spring:
  r2dbc:
    url: r2dbc:h2:mem:///shopdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  h2:
    console:
      enabled: true

  thymeleaf:
    cache: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
server:
  port: 8080
